name: twohungryguys
favicon: null
layout_spectrum: 0.77789
typography_spectrum: 0.20513854757882655
title: twohungryguys
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#080904'
    - '#554a58'
    - '#e39968'
    - '#999594'
  brandStrength: 0.625
  lightness: 0.3196883697528392
  saturation: 0.7333707557991147
  rhythmicContrast: 0.75
purpose: []
